export const data = [
    {id :1,
        name: 'American Pyscho',
        year: '2000',
        img: 'assets/images/sigma.jpg',
        nation: 'USA',
        infor: 'American Psycho is a 2000 horror film directed by Mary Harron, who co-wrote the screenplay with Guinevere Turner. Based on the 1991 novel by Bret Easton Ellis, it stars Christian Bale as Patrick Bateman, a New York City investment banker who leads a double life as a serial killer.'
    },
    {id :2,
        name: 'Bố Già',
        year: '2021',
        img: 'assets/images/tra.jpg',
        nation: 'Vietnam',
        infor: 'The old father is a 2021 Vietnamese comedy-drama film co-directed by Tran Thanh and Vu Ngoc Dang. The film is produced by Thao Nguyen, based on the script written by Tran Thanh, Kalei An Nhi and Aquay.The Godfather is a 2021 Vietnamese comedy-drama film co-directed by Tran Thanh and Vu Ngoc Dang. The film is produced by Thao Nguyen, based on the script written by Tran Thanh, Kalei An Nhi and Aquay.'
    },
    {id :3,
        name: 'Puss in boots: the last wish',
        year: '2022',
        img: 'assets/images/cat.jpg',
        nation: 'USA',
        infor: 'When Puss in Boots discovers that his passion for adventure has taken its toll and he has burned through eight of his nine lives, he launches an epic journey to restore them by finding the mythical Last Wish.'
    },
    {id :4,
        name: 'The Boys',
        year: '2019',
        img: 'assets/images/boy.jpg',
        nation: 'USA',
        infor: 'The Boys is an American superhero television series developed by Eric Kripke for Amazon Prime Video. Based on the comic book of the same name by Garth Ennis and Darick Robertson, it follows the eponymous team of vigilantes as they combat superpowered individuals who abuse their abilities.'
    },
    {id :5,
        name: 'The Nun',
        year: '2019',
        img: 'assets/images/nun.jpg',
        nation: 'USA',
        infor: 'The Nun is a 2018 American supernatural horror film directed by Corin Hardy and written by Gary Dauberman, from an original story by Dauberman and James Wan.'
    },
    {id :6,
        name: 'Avengers: Infinity war',
        year: '2019',
        img: 'assets/images/ttxvn_avengers.jpg',
        nation: 'USA',
        infor: 'Avengers: Infinity War is a 2018 American superhero film based on Marvel Comics characters.'
    },
    {id :7,
        name: 'Joker',
        year: '2019',
        img: 'assets/images/joker.jpg',
        nation: 'USA',
        infor: 'Set in 1981, it follows Arthur Fleck, a failed clown and aspiring stand-up comic whose descent into mental illness and nihilism inspires a violent countercultural revolution against the prosperous in a decaying Gotham City.'
    },
    {id :8,
        name: 'Kung Fu Panda 2',
        year: 2011,
        img: 'assets/images/povsshen.jpg',
        nation: "Chinese",
        infor: 'Kung Fu Panda 2 is a 2011 American computer-animated martial arts comedy film produced by DreamWorks Animation and distributed by Paramount Pictures. The film is the sequel to Kung Fu Panda (2008) and the second installment in the Kung Fu Panda franchise.'
    },
    {id :9,
        name: 'The Frozen Flower',
        year: 2008,
        img: 'assets/images/flower.jpg',
        nation: "Korea",
        infor: 'A Frozen Flower is a 2008 South Korean film directed by Yoo Ha. The film tells the story of a love triangle with homosexuality and bisexuality that violates royal laws. The setting of the film is the Goryeo Dynasty with actors Jo In Sung, Ju Jin Mo and Song Ji Hyo'
    },
];